name: 云端提取指定分区

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/tissot/20230425/lineage-19.1-20230425-nightly-tissot-signed.zip'
      part:
        description: '提取分区'
        required: true
        default: 'vendor'


jobs:
  YIJIANTIQU:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          start_time=$(date +%s)
          sudo apt-get update
          sudo apt install aria2
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV

      - name: 提取镜像
        run: |
          cd ~
          mkdir 1
          cd ~
          wget https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz
          tar -zxvf payload-dumper-go_1.2.2_linux_amd64.tar.gz
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          ./extractor.sh firmware.zip
          chmod +x payload-dumper-go
          ./payload-dumper-go -p "${{ github.event.inputs.part }}" -o ~/1 firmware.zip
          cd ${{ github.workspace }}
          end_time=$(date +%s)
          execution_time=$((end_time - start_time))
          touch info.md
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "ROM 下载直链：${{ github.event.inputs.rom_url }}" >> info.md
          echo "本次自定义提取分区为：${{ github.event.inputs.part }}" >> info.md
          echo "本次提取时长为 $execution_time 秒" >> info.md

      - name: 上传镜像及相关信息
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "~/1/*"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
            token: ${{ secrets.GITHUB_TOKEN }}

